### ISSUE TITLE
Content of .rdf-file missing for zlib-1.2.12

### ISSUE THREAD

**Issue by LeChasseur** [Open-Source-Compliance/package-analysis#73]
The following file does not have content:
https://github.com/Open-Source-Compliance/package-analysis/blob/main/analysed-packages/zlib/version-1.2.12/zlib-1.2.12.spdx.rdf.xml

**Comment by OliverFendt** [comment]
Good catch @LeChasseur. Thank you very much for spotting this.
There was a white space in the path of the package in the tag value file, due to this the rdf generation was obviously not correct. I corrected the path and generated the rdf file.
Please check it, I will close the issue once you checked it and you think it is ok.

**Comment by OliverFendt** [comment]
I added the rdf file. I close the issue now
